### ISSUE TITLE
Setting "<rank_column>_position" to :down doesn't get reset after save.

### ISSUE THREAD

**Issue by joshuapinter** [brendon/ranked-model#100]
So if you keep re-saving the same object it will keep getting pushed down, which is obscure and probably undesirable effect.

Example:

``` bash
> @duck.row_order
# => 1

> @duck.update_attribute :row_order_position, :down
# => :down

> @duck.row_order
# => 2

> @duck.row_order_position
# => :down

> @duck.save
# => true

> @duck.row_order
# => 3

> @duck.save
# => true

> @duck.row_order
# => 4
```

**Comment by brendon** [comment]
This might have been fixed in the latest version since we materialise the position as an integer on save. Feel free to let me know if not.
