### ISSUE TITLE
NonNilColumnDefault breaks running app when rank column has a default value

### ISSUE THREAD

**Issue by vanboom** [brendon/ranked-model#180]
The logic for raising the NonNilColumnDefault breaks a running application from loading when the ranked column has a default value. The exception does not even allow rake to run. 

Suggestion:  change to something non-destructive to raise awareness of this dependency without breaking the application.

**Comment by brendon** [comment]
Hi @vanboom, it's intended to be annoying. It's not supported and can cause subtle problems so I think it's best that it fatally fails. I'd assume you'd only find yourself in this position upon upgrading `ranked-model` or commencing development. In both cases I think it'd be important to know of this problem early on and rectify it.

What was your situation? :)

**Comment by brendon** [comment]
Another idea is to allow the error raise to be silenced by an initialiser?

**Comment by brendon** [comment]
Closing this for now. See my comment in the PR.
