### ISSUE TITLE
Publish new version to RubyGems

### ISSUE THREAD

**Issue by dankimio** [brendon/ranked-model#183]

**Comment by brendon** [comment]
Hi @dankimio, please realise that behind the issues system is a real person who maintains this gem in his own time for no pay. I don't know if you realise, but "Publish new version to RubyGems" sounds very demanding. I don't mind releasing a new version, but perhaps something like this would come across better next time:

Title: New version release
Body: Hi there, I was wondering if you wouldn't mind releasing a new version containing the recent fix (https://github.com/brendon/ranked-model/commit/ac4079ebeda2a10b79fe6a488ddff45b0c5a5c46)?

As it stands, I'm having trouble getting bundler to install all the required gems to make a release on this M1 Mac. I'll have to take a look at it when I have some more time next week. In the meantime, you can pin to the master branch in bundler if you need that fix.

**Comment by dankimio** [comment]
Hey, sorry if it came off demanding. I opened this issue purely for bug tracking reasons. Only for the maintainers to know that there is such an issue. No intention of pressuring or speeding up the release of the new version at all.

**Comment by brendon** [comment]
Thanks @dankimio, I appreciate the response :) I would normally have released straight away but it’s always a struggle to bundle with the M1 cpu.

**Comment by fschwahn** [comment]
For what it's worth, I've been running the master branch since December (because of ac4079ebeda2a10b79fe6a488ddff45b0c5a5c46) and haven't had any issues.

**Comment by brendon** [comment]
Hi @dankimio, just letting you know that `0.4.8` has been released. :)
