### ISSUE TITLE
how to find neighbor?

### ISSUE THREAD

**Issue by laptopmutia** [brendon/ranked-model#197]
if I have an object can I find what is next and previous of it?

**Comment by laptopmutia** [comment]
yeah I have see that snippet and code from another issues and from spec test but I don't know how to use it on my code

if I have a 
```ruby
class Questionnaire < ApplicationRecord
  has_many :sections, dependent: :destroy
  has_many :respons, dependent: :destroy
  has_rich_text :description
  validates_uniqueness_of :closed, unless: :closed, message: "there is active questionnaire"

  def self.last_active
    self.where(closed: false).order(created_at: :desc).first
  end
end
```

```ruby
class Section < ApplicationRecord
  include RankedModel
  scope :root_section, -> { where(parent_id: nil) }
  ranks :section_order,
        scope: :root_section,
        with_same: :questionnaire_id
  ranks :sub_section_order,
        if: :sub_section?,
        with_same: :parent_id
  validates :name, presence: true
  has_rich_text :description
  has_many :questions, dependent: :destroy
  belongs_to :questionnaire
  has_many :sub_sections, class_name: "Section", foreign_key: "parent_id", dependent: :destroy
  belongs_to :parent_section, class_name: "Section", optional: true

  def sub_section?
    !self.parent_id.nil?
  end
end
```

how to find the section current_at position and its neighbor?

**Comment by laptopmutia** [comment]
@brendon your response is too fast, I really appreciate it

okay heres my code to get adjacent/neighbor

first get the model

```ruby
@current_section = Questionnaire.first.sections.root_section.rank(:section_order).third
```

then get the position by using  `section_order_rank`
```ruby
@current_section_rank = @current_section.section_order_rank
```

then I want to use current_at_position  it said 
````method_missing': undefined method `current_at_position' for #<ActiveRecord::Relation```

```ruby
Section.rank(:section_order).current_at_position(2)
```
same error throwed with this syntax too
```
Section.root_section.rank(:section_order).current_at_position(1)
```

so is when I try to use ranker instead rank
like in this spec https://github.com/brendon/ranked-model/blob/master/spec/duck-model/lots_of_ducks_spec.rb#L35

**Comment by brendon** [comment]
This may not be possible on closer inspection (at least there's no API in this gem for that). We do do it internally when reordering things:

```
def find_next_two _rank
        ordered_instances = finder.where(instance_class.arel_table[ranker.column].gt _rank).limit(2)
...
```

You may have to resort to something like that. The problem is that this gem doesn't clutter the model's namespace like acts_as_list does, so I'm loathe to do that now. It could be that the ranker could be extended to allow for this though.

**Comment by laptopmutia** [comment]
somehow I could manage to find the adjacent + 1 and -1 of current position but I don't understand the code at all and I afraid that is gonna break in production

first get current 
```ruby
@current_section = Questionnaire.first.sections.root_section.rank(:section_order).third
```
then to find +1 adjacent
 ```ruby Section.root_section.ranker(:section_order).with(@current_section).current_at_position(@current_section.section_order_rank).instance
```

and to find -1 adjacent
 ```ruby Section.root_section.ranker(:section_order).with(@current_section).current_at_position(@current_section.section_order_rank-1).instance
```

I think I cannot use find_next_two since it is private method

**Comment by brendon** [comment]
That's correct, I was just showing it as an example. Sounds like you've figured it out?

**Comment by laptopmutia** [comment]
I'm end up using acts_as_list as using this pretty much gives me more works to do, I think we could close this

**Comment by brendon** [comment]
No worries @laptopmutia. `acts_as_list` is another good option.
