### ISSUE TITLE
Updating the readme for beginners like myself

### ISSUE THREAD

**Issue by ghost** [brendon/ranked-model#31]
Not really an issue, but I believe, for certain people, a slightly more detailed readme could be of use in diagnosing some of the issues I had when setting this (otherwise very easy to use) plugin up.

For instance, you include having to set up the row_order column as an integer, but don't mention having to also set up a row_order_position column as an integer.

Also, setting those both to default to 0 instead of nil tripped me up for a short while.

Obviously not huge issues, but it might help adoption by those of us who might have otherwise given up on a great plugin because they weren't sure where to look for the solution (the answer being in the console and logs to see where the problem was for me, and then look at the source code to see what was expected- but again, this is merely to help out beginners.

Let me know what you think - if you're busy, I'd be happy to write a slightly modified readme and submit it to you.

Regardless, thanks for the great plugin.

Steve

**Comment by brendon** [comment]
Closing this. I assume everyone has moved on. If you want to improve the documentation I'll always happily accept PRs for that :D
