### ISSUE TITLE
Provide a way to change min_rank and max_rank values

### ISSUE THREAD

**Issue by leonelgalan** [brendon/ranked-model#43]
This are currently defined as

``` ruby
  # Signed MEDIUMINT in MySQL
  #
  MAX_RANK_VALUE = 8388607
  MIN_RANK_VALUE = -8388607
```

in https://github.com/mixonic/ranked-model/blob/master/lib/ranked-model.rb#L8

But it will be nice if we could change them as options of the `rank` method. E.g.:

``` ruby
ranks ..., min_rank_value: 0, max_rank_value: 2147483647
```

This to play nice with other gems ([closure_tree](https://github.com/mceachen/closure_tree#deterministic-ordering)'s deterministic ordering) and to increase the range if necessary. For example [postgre's integer](http://www.postgresql.org/docs/8.3/interactive/datatype-numeric.html#DATATYPE-NUMERIC-TABLE) ranges from -2147483648 to +2147483647.

**Comment by leomayleomay** [comment]
I am wondering if you could do the following to set the MIN and MAX value

```
RankedModel::MIN_RANK_VALUE = 0
RankedModel::MAX_RANK_VALUE = 8388607*2
```

**Comment by brendon** [comment]
Closing due to age. Open to PRs on this concept though.
