### ISSUE TITLE
Gem doesn't load in Rails 4 engine.gemspec

### ISSUE THREAD

**Issue by bbugh** [brendon/ranked-model#72]
Hi, since a Rails 4 --mountable engine is a .gemspec, and since the recommended place to put gems is in the .gemspec, this is more bug-ish than a bug. I've seen it in other libraries too.

In the engine_name.gemspec file, this loads but is inaccessible by Rails.
`s.add_dependency 'ranked-model'`

The only way to fix it is to put it into the Gemfile. Kind of a bummer when all of the other gems are in the gemspec!

**Comment by mat2maa** [comment]
Just ran across the same issue. The following is inspired by [this](http://stackoverflow.com/a/5850503/1542367 "this") and using Ruby 1.9.3 and Rails 3.2.13.

I got it to work without error by first adding `s.add_dependency 'ranked-model'` to `test_plugin.gemspec`, following the example set out by @bbugh, and then adding:
```
require 'ranked-model'
```
to the top of `lib/test_plugin/engine.rb`.

**Comment by brendon** [comment]
Open to fixing this if it's still an issue. Let me know and I'll reopen.
