### ISSUE TITLE
Error on trying to sort records with row_order = null

### ISSUE THREAD

**Issue by stgeneral** [brendon/ranked-model#73]
``` ruby
class AddRowOrderToImages < ActiveRecord::Migration
  def change
    add_column :images, :row_order, :integer
  end
end

class Image < ActiveRecord::Base
  # ...
  include RankedModel
  ranks :row_order, with_same: [:attachable_id, :attachable_type]
end

@image.update_attribute :row_order_position, 0 
# raises NoMethodError (undefined method `-' for nil:NilClass):
```

I've solved it migrating to :null => false, :default => 0 for row_order column.

Solutions:
- update README with example migration with specified :null => false, :default => 0
- respect null value during row_order recalculations.

**Comment by brendon** [comment]
I'm not sure if setting a default value for that column is supported from an ideological point of view unless you set it to the maximum or minimum value?

**Comment by brendon** [comment]
Having a default column value is not allowed. We check for this now.
