### ISSUE TITLE
Basic methods?

### ISSUE THREAD

**Issue by axhamre** [brendon/ranked-model#80]
I have to switch gem from acts_as_list to ranked-model, because I need to restrict the scope.

I cannot find some of the basic methods for ranked-model though.

How do I get the position of an item relative to the others? (In AAL it's simply: `position`.)

And how would I remove an item to be included in the ranking set? (In AAL: `remove_from_list`.)

**Comment by brendon** [comment]
Check out my new gem for an alternative: https://github.com/brendon/positioning

10 years later but...
