### ISSUE TITLE
Issue with dependent objects with same sequence and adding new object

### ISSUE THREAD

**Issue by PallaviTS** [brendon/ranked-model#84]
I have two objects, parent and child which has same sequence number
![screenshot 2014-09-09 10 16 04](https://cloud.githubusercontent.com/assets/3283172/4196804/73e1d904-37dc-11e4-9251-dda8e1f9b827.png)

Now i create a new object , Im expecting the sequence of this to be greater than the existing objects , but the sequence is 0  

![screenshot 2014-09-09 10 16 33](https://cloud.githubusercontent.com/assets/3283172/4196820/cd303410-37dc-11e4-9800-bf561635a6a8.png)

**Comment by brendon** [comment]
Closing due to age.
