### ISSUE TITLE
wrong attribute update

### ISSUE THREAD

**Issue by tommybernaciak** [brendon/ranked-model#86]
This is very nice gem, but has a liitle bug. Attribute used for ranking is wrongly updated. I found this when implementing some sortable tables in rails. List of users is ordered by position - attribute use by ranked-model. Here is how the table look like:
![table1](https://cloud.githubusercontent.com/assets/5927665/4370401/48a45c58-4308-11e4-9162-a1c53a25a0eb.png)

After taking element with position 15 to 5 every element gets updated, but look what happened to element with position > 15, it gets also added 1 so now there is a break (17th element after 15th, no element with position 16).
![table2](https://cloud.githubusercontent.com/assets/5927665/4370402/48ac16aa-4308-11e4-8b55-d6e67c66dab8.png)
After some modification of order it gets really annoying, because you dont know exactly how its going to work.

Another mistake is that it doesnt work for two elements at all. Position is getting max integer and min integer value.

I am using Postgres with Rails 4, if you want to see my implementation I can add link to the project.

**Comment by brendon** [comment]
There was a bug that may have caused this. It was fixed a long time ago.
