### ISSUE TITLE
Touch the model when reassigning

### ISSUE THREAD

**Issue by adamcooper** [brendon/ranked-model#87]
Hi,

We are looking at using this gem and it looks like a great fit.  We would like to be able to tell what models have changed as a result of the rebalancing.  This is because we store the ordering column in a search index and don't want to have to update the entire list when a rebalance occurs.

Would you take a patch upstream that included a config option `touch_record_when_rebalancing`?

Thanks,
Adam

**Comment by brendon** [comment]
Closing this for now. Happy to look at it again if there's a need.
