### ISSUE TITLE
suggesting add index on row_order

### ISSUE THREAD

**Issue by jhjwind** [brendon/ranked-model#95]
we use rank model on our markets table. We didn't have an index on the row_order and ended up with lots of seq scan on the row_roder column. I suggest adding index on the row_order column. It would be great if you can put it in the readme. 

```
 SELECT "markets".* FROM "markets"   ORDER BY "markets"."row_order" ASC                                                                                                                                     
```

**Comment by brendon** [comment]
Happy to accept a PR about this for the Readme if it hasn't already been done in the meantime. Closing for now.
